---
artifacts:
  files:
    - artifact/*.zip
    - samTemplate.yaml
phases:
  build:
    commands:
      - "npm run build"
  install:
    commands:
      - "npm install"
      - "aws cloudformation package --template-file cloudformation.yaml --s3-bucket bin-master --output-template-file samTemplate.yaml"
version: 0.2
